name = "QuadrupedController"
uuid = "0a0771de-1099-46b6-8518-8474b76bc44f"
authors = ["Mark Bowers <mark_bowers@live.com> and contributors"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
Conda = "1.5"
PyCall = "1.91"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
